name: Lo Chuen Yan
favicon: null
layout_spectrum: 0.34296479914337397
typography_spectrum: 0.5952162751927972
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8179840908851475
  lightness: 0.3053826193790883
  saturation: 0.12089122389443219
  rhythmicContrast: 0.5527189166750759
purpose: []
