typography_spectrum: 0.5952162751927972
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8179840908851475
  lightness: 0.3053826193790883
  saturation: 0.12089122389443219
  rhythmicContrast: 0.5527189166750759
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.34296479914337397
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Lo Chuen Yan
  email: lochuenyan@gmail.com
  url: 'http://www.chuenyan.com'
name: Lo Chuen Yan
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
