typography_spectrum: 0.26579
color:
  brandColors:
    - '#040000'
    - '#4e0000'
    - '#ba6b22'
    - '#792400'
    - '#dfb468'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.25
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.07029
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Lo Chuen Yan
  email: lochuenyan@gmail.com
  url: 'http://www.chuenyan.com'
name: Lo Chuen Yan
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Lo Chuen Yan
    url: 'http://www.chuenyan.com'
    type: external
favicon: null
title: Lo Chuen Yan
description: Lo Chuen Yan
purpose: []
